export const businessPartners = [
    {
        id: 'bp-001',
        tipo: 'CLIENTE',
        nombre_legal: 'Distribuidora El Progreso S.A.',
        nombre_comercial: 'El Progreso',
        rtn: '05011997000123',
        email: 'compras@elprogreso.hn',
        telefono: '+504 2221-0001',
        direccion: 'Col. Las Torres, Tegucigalpa, MDC',
        condicion_pago: '30 días',
        limite_credito: 200000,
        estado: true,
    },
    {
        id: 'bp-002',
        tipo: 'PROVEEDOR',
        nombre_legal: 'Importaciones Caribe Ltda.',
        nombre_comercial: 'Caribe Imports',
        rtn: '08011990000456',
        email: 'ventas@caribeimports.hn',
        telefono: '+504 2556-1234',
        direccion: 'Zona Industrial, San Pedro Sula',
        condicion_pago: '15 días',
        limite_credito: 0,
        estado: true,
    },
    {
        id: 'bp-003',
        tipo: 'AMBOS',
        nombre_legal: 'Servicios Logísticos del Norte S.R.L.',
        nombre_comercial: 'LogiNorte',
        rtn: '12011985000789',
        email: 'operaciones@loginorte.hn',
        telefono: '+504 9876-5432',
        direccion: 'Blvd. Centroamérica, Choloma',
        condicion_pago: 'Contado',
        limite_credito: 50000,
        estado: true,
    },
    {
        id: 'bp-004',
        tipo: 'CLIENTE',
        nombre_legal: 'Supermercados Unidad Familiar S.A.',
        nombre_comercial: 'UniFamily',
        rtn: '07011992000321',
        email: 'proveedores@unifamily.hn',
        telefono: '+504 2244-9000',
        direccion: 'Centro Comercial UniPlaza, TGU',
        condicion_pago: '30 días',
        limite_credito: 500000,
        estado: true,
    },
    {
        id: 'bp-005',
        tipo: 'PROVEEDOR',
        nombre_legal: 'Plásticos y Empaques del Valle',
        nombre_comercial: 'EmpaveValle',
        rtn: '03011978000654',
        email: 'info@empavevalle.hn',
        telefono: '+504 2765-3311',
        direccion: 'Finca El Valle, La Lima, Cortés',
        condicion_pago: 'Contado',
        limite_credito: 0,
        estado: false,
    },
    {
        id: 'bp-006',
        tipo: 'CLIENTE',
        nombre_legal: 'Farmacias Central S.A. de C.V.',
        nombre_comercial: 'FarmaCentral',
        rtn: '09011996000987',
        email: 'pedidos@farmacentral.hn',
        telefono: '+504 2233-4455',
        direccion: 'Col. Palmira, Tegucigalpa',
        condicion_pago: '15 días',
        limite_credito: 150000,
        estado: true,
    },
];
