export const expenses = [
    {
        id: 'exp-001',
        date: '2026-02-05',
        description: 'Compra de material de oficina',
        department_id: 'dept-001',
        category_id: 'cat-001',
        subcategory_id: 'sub-001',
        division_id: 'div-001',
        amount: 4500.00,
        status: 'Aprobado',
        notes: 'Papelería y consumibles',
    },
    {
        id: 'exp-002',
        date: '2026-02-10',
        description: 'Combustible vehículo de reparto',
        department_id: 'dept-002',
        category_id: 'cat-002',
        subcategory_id: 'sub-003',
        division_id: 'div-002',
        amount: 8200.00,
        status: 'Aprobado',
        notes: 'Carga completa del tanque',
    },
    {
        id: 'exp-003',
        date: '2026-02-14',
        description: 'Mantenimiento de bodega',
        department_id: 'dept-003',
        category_id: 'cat-003',
        subcategory_id: 'sub-005',
        division_id: 'div-001',
        amount: 15000.00,
        status: 'Pendiente',
        notes: 'Pintura y reparaciones menores',
    },
    {
        id: 'exp-004',
        date: '2026-02-18',
        description: 'Suscripción software contable',
        department_id: 'dept-001',
        category_id: 'cat-004',
        subcategory_id: 'sub-007',
        division_id: 'div-003',
        amount: 3200.00,
        status: 'Aprobado',
        notes: 'Pago mensual',
    },
    {
        id: 'exp-005',
        date: '2026-02-22',
        description: 'Capacitación del personal',
        department_id: 'dept-004',
        category_id: 'cat-005',
        subcategory_id: 'sub-009',
        division_id: 'div-002',
        amount: 22000.00,
        status: 'Rechazado',
        notes: 'Taller de logística avanzada',
    },
    {
        id: 'exp-006',
        date: '2026-02-25',
        description: 'Publicidad en redes sociales',
        department_id: 'dept-005',
        category_id: 'cat-006',
        subcategory_id: 'sub-011',
        division_id: 'div-003',
        amount: 6800.00,
        status: 'Aprobado',
        notes: 'Campaña de mes de febrero',
    },
    {
        id: 'exp-007',
        date: '2026-03-02',
        description: 'Reparación montacargas',
        department_id: 'dept-003',
        category_id: 'cat-003',
        subcategory_id: 'sub-006',
        division_id: 'div-001',
        amount: 38500.00,
        status: 'Pendiente',
        notes: 'Cambio de piezas hidráulicas',
    },
    {
        id: 'exp-008',
        date: '2026-03-05',
        description: 'Pago telefonía corporativa',
        department_id: 'dept-001',
        category_id: 'cat-004',
        subcategory_id: 'sub-008',
        division_id: 'div-001',
        amount: 5400.00,
        status: 'Aprobado',
        notes: '6 líneas móviles',
    },
];
