export const inventoryMovements = [
    {
        id: 'mov-001',
        fecha: '2026-02-10',
        tipo: 'ENTRADA',
        product_id: 'prod-001',
        warehouse_id: 'wh-001',
        warehouse_destino_id: null,
        cantidad: 50,
        costo_unitario: 250.00,
        referencia: 'Compra inicial stock',
        observacion: 'Recepción bodega central',
    },
    {
        id: 'mov-002',
        fecha: '2026-02-12',
        tipo: 'ENTRADA',
        product_id: 'prod-002',
        warehouse_id: 'wh-001',
        warehouse_destino_id: null,
        cantidad: 250,
        costo_unitario: 28.00,
        referencia: 'OC-000001',
        observacion: 'Compra inicial cajas cartón',
    },
    {
        id: 'mov-003',
        fecha: '2026-02-14',
        tipo: 'SALIDA',
        product_id: 'prod-001',
        warehouse_id: 'wh-001',
        warehouse_destino_id: null,
        cantidad: 5,
        costo_unitario: 250.00,
        referencia: 'OV-000001',
        observacion: 'Despacho cliente El Progreso',
    },
    {
        id: 'mov-004',
        fecha: '2026-02-15',
        tipo: 'TRANSFERENCIA',
        product_id: 'prod-001',
        warehouse_id: 'wh-001',
        warehouse_destino_id: 'wh-002',
        cantidad: 8,
        costo_unitario: 250.00,
        referencia: 'TRANSF-001',
        observacion: 'Trasaldo a bodega SPS',
    },
    {
        id: 'mov-005',
        fecha: '2026-02-18',
        tipo: 'AJUSTE',
        product_id: 'prod-006',
        warehouse_id: 'wh-001',
        warehouse_destino_id: null,
        cantidad: 10,
        costo_unitario: 72.00,
        referencia: 'AJ-INV-001',
        observacion: 'Ajuste de inventario físico',
    },
    {
        id: 'mov-006',
        fecha: '2026-02-20',
        tipo: 'ENTRADA',
        product_id: 'prod-003',
        warehouse_id: 'wh-002',
        warehouse_destino_id: null,
        cantidad: 5,
        costo_unitario: 980.00,
        referencia: 'OC-000002',
        observacion: 'Compra aceite hidráulico SPS',
    },
];
