export const payments = [
    {
        id: 'pay-001',
        date: '2026-02-05',
        reference: 'PAY-000001',
        partner_id: 'bp-001',
        partner: 'Distribuidora El Progreso S.A.',
        tipo: 'COBRO',
        amount: 95000.00,
        method: 'Transferencia',
        account: '1101 - Caja General',
        document_ref: 'OV-000001',
        status: 'Aplicado',
        notes: 'Cobro de factura 001',
    },
    {
        id: 'pay-002',
        date: '2026-02-10',
        reference: 'PAY-000002',
        partner_id: 'bp-002',
        partner: 'Importaciones Caribe Ltda.',
        tipo: 'PAGO',
        amount: 8400.00,
        method: 'Cheque',
        account: '1102 - Banco Atlántida',
        document_ref: 'CQ-000001',
        status: 'Aplicado',
        notes: 'Pago de cotizacion de compra',
    },
    {
        id: 'pay-003',
        date: '2026-02-15',
        reference: 'PAY-000003',
        partner_id: 'bp-004',
        partner: 'Supermercados Unidad Familiar S.A.',
        tipo: 'COBRO',
        amount: 7590.00,
        method: 'Depósito',
        account: '1102 - Banco Atlántida',
        document_ref: 'OV-000002',
        status: 'Aplicado',
        notes: '',
    },
    {
        id: 'pay-004',
        date: '2026-02-20',
        reference: 'PAY-000004',
        partner_id: 'bp-003',
        partner: 'Servicios Logísticos del Norte S.R.L.',
        tipo: 'PAGO',
        amount: 35810.00,
        method: 'Transferencia',
        account: '1102 - Banco Atlántida',
        document_ref: 'CQ-000002',
        status: 'Pendiente',
        notes: 'Pendiente aprobación gerencia',
    },
    {
        id: 'pay-005',
        date: '2026-02-28',
        reference: 'PAY-000005',
        partner_id: 'bp-006',
        partner: 'Farmacias Central S.A. de C.V.',
        tipo: 'COBRO',
        amount: 8338.75,
        method: 'Efectivo',
        account: '1101 - Caja General',
        document_ref: 'OV-000003',
        status: 'Aplicado',
        notes: '',
    },
    {
        id: 'pay-006',
        date: '2026-03-03',
        reference: 'PAY-000006',
        partner_id: 'bp-001',
        partner: 'Distribuidora El Progreso S.A.',
        tipo: 'COBRO',
        amount: 42000.00,
        method: 'Transferencia',
        account: '1102 - Banco Atlántida',
        document_ref: 'OV-000004',
        status: 'Pendiente',
        notes: 'En proceso de verificación',
    },
];
