export const products = [
    {
        id: 'prod-001',
        sku: 'ALM-001',
        nombre: 'Almendra Natural 1kg',
        descripcion: 'Almendra natural sin tostar, bolsa de 1 kilogramo',
        categoria: 'Alimentos',
        uom: 'KG',
        impuesto_pct: 15,
        precio_venta: 380.00,
        costo_compra: 250.00,
        stock_minimo: 10,
        activo: true,
    },
    {
        id: 'prod-002',
        sku: 'EMP-002',
        nombre: 'Caja Cartón Triple Canal 60x40',
        descripcion: 'Caja corrugada triple canal para empaque industrial',
        categoria: 'Empaques',
        uom: 'UND',
        impuesto_pct: 15,
        precio_venta: 45.00,
        costo_compra: 28.00,
        stock_minimo: 50,
        activo: true,
    },
    {
        id: 'prod-003',
        sku: 'LUB-003',
        nombre: 'Aceite Hidráulico ISO 46 – 20L',
        descripcion: 'Aceite hidráulico de alto rendimiento 20 litros',
        categoria: 'Lubricantes',
        uom: 'LT',
        impuesto_pct: 15,
        precio_venta: 1450.00,
        costo_compra: 980.00,
        stock_minimo: 5,
        activo: true,
    },
    {
        id: 'prod-004',
        sku: 'TECH-004',
        nombre: 'Escáner Código de Barras USB',
        descripcion: 'Lector de código de barras 1D/2D USB plug-and-play',
        categoria: 'Tecnología',
        uom: 'UND',
        impuesto_pct: 15,
        precio_venta: 2200.00,
        costo_compra: 1400.00,
        stock_minimo: 3,
        activo: true,
    },
    {
        id: 'prod-005',
        sku: 'PLAST-005',
        nombre: 'Paleta Plástica 120x100 cm',
        descripcion: 'Paleta industrial de polietileno de alta densidad',
        categoria: 'Empaques',
        uom: 'UND',
        impuesto_pct: 15,
        precio_venta: 850.00,
        costo_compra: 560.00,
        stock_minimo: 20,
        activo: true,
    },
    {
        id: 'prod-006',
        sku: 'CAFE-006',
        nombre: 'Café Molido Especial 500g',
        descripcion: 'Café hondureño premium, tostado y molido, bolsa 500g',
        categoria: 'Alimentos',
        uom: 'UND',
        impuesto_pct: 0,
        precio_venta: 120.00,
        costo_compra: 72.00,
        stock_minimo: 30,
        activo: true,
    },
    {
        id: 'prod-007',
        sku: 'EMP-007',
        nombre: 'Stretch Film 45cm x 300m',
        descripcion: 'Film estirable para paletizado, rollo de 300 metros',
        categoria: 'Empaques',
        uom: 'UND',
        impuesto_pct: 15,
        precio_venta: 280.00,
        costo_compra: 180.00,
        stock_minimo: 15,
        activo: false,
    },
    {
        id: 'prod-008',
        sku: 'TECH-008',
        nombre: 'Etiquetadora Térmica 4" USB',
        descripcion: 'Impresora de etiquetas térmica directa 4 pulgadas',
        categoria: 'Tecnología',
        uom: 'UND',
        impuesto_pct: 15,
        precio_venta: 4800.00,
        costo_compra: 3200.00,
        stock_minimo: 2,
        activo: true,
    },
];
