export const purchaseQuotes = [
    {
        id: 'cq-001',
        numero_documento: 'CQ-000001',
        fecha: '2026-02-12',
        proveedor_id: 'bp-002',
        moneda: 'HNL',
        estado: 'Aprobada',
        observaciones: 'Cotización evaluada y aprobada',
        lineas: [
            {
                id: 'cql-001',
                producto_id: 'prod-002',
                descripcion: 'Caja Cartón Triple Canal 60x40',
                cantidad: 300,
                costo_unitario: 28.00,
                impuesto_pct: 15,
            },
        ],
    },
    {
        id: 'cq-002',
        numero_documento: 'CQ-000002',
        fecha: '2026-02-17',
        proveedor_id: 'bp-003',
        moneda: 'USD',
        estado: 'Enviada',
        observaciones: 'Enviada por correo electrónico',
        lineas: [
            {
                id: 'cql-002',
                producto_id: 'prod-003',
                descripcion: 'Aceite Hidráulico ISO 46 – 20L',
                cantidad: 20,
                costo_unitario: 980.00,
                impuesto_pct: 15,
            },
            {
                id: 'cql-003',
                producto_id: 'prod-005',
                descripcion: 'Paleta Plástica 120x100 cm',
                cantidad: 50,
                costo_unitario: 560.00,
                impuesto_pct: 15,
            },
        ],
    },
    {
        id: 'cq-003',
        numero_documento: 'CQ-000003',
        fecha: '2026-02-21',
        proveedor_id: 'bp-002',
        moneda: 'HNL',
        estado: 'Borrador',
        observaciones: '',
        lineas: [
            {
                id: 'cql-004',
                producto_id: 'prod-001',
                descripcion: 'Almendra Natural 1kg',
                cantidad: 100,
                costo_unitario: 250.00,
                impuesto_pct: 15,
            },
        ],
    },
    {
        id: 'cq-004',
        numero_documento: 'CQ-000004',
        fecha: '2026-02-22',
        proveedor_id: 'bp-005',
        moneda: 'HNL',
        estado: 'Cancelada',
        observaciones: 'Proveedor inhabilitado',
        lineas: [
            {
                id: 'cql-005',
                producto_id: 'prod-007',
                descripcion: 'Stretch Film 45cm x 300m',
                cantidad: 30,
                costo_unitario: 180.00,
                impuesto_pct: 15,
            },
        ],
    },
];
