export const roles = [
    {
        id: 'rol-001',
        name: 'Administrador',
        description: 'Acceso total al sistema',
        userCount: 2,
        active: true,
        permissions: ['dashboard', 'socios', 'inventario', 'ventas', 'compras', 'finanzas', 'gastos', 'configuracion'],
    },
    {
        id: 'rol-002',
        name: 'Ventas',
        description: 'Gestión de ofertas de venta y clientes',
        userCount: 4,
        active: true,
        permissions: ['dashboard', 'socios', 'ventas', 'inventario'],
    },
    {
        id: 'rol-003',
        name: 'Compras',
        description: 'Gestión de cotizaciones de compra y proveedores',
        userCount: 2,
        active: true,
        permissions: ['dashboard', 'socios', 'compras', 'inventario'],
    },
    {
        id: 'rol-004',
        name: 'Bodega',
        description: 'Control de inventario, almacenes y movimientos',
        userCount: 3,
        active: true,
        permissions: ['dashboard', 'inventario'],
    },
    {
        id: 'rol-005',
        name: 'Contabilidad',
        description: 'Módulo financiero y reportes',
        userCount: 2,
        active: true,
        permissions: ['dashboard', 'finanzas', 'gastos'],
    },
    {
        id: 'rol-006',
        name: 'Solo Lectura',
        description: 'Acceso de consulta sin modificaciones',
        userCount: 1,
        active: false,
        permissions: ['dashboard'],
    },
];
