export const salesOffers = [
    {
        id: 'ov-001',
        numero_documento: 'OV-000001',
        fecha: '2026-02-15',
        cliente_id: 'bp-001',
        vendedor: 'Juan Pérez',
        almacen_id: 'wh-001',
        estado: 'Aprobada',
        observaciones: 'Entrega urgente solicitada',
        lineas: [
            {
                id: 'ovl-001',
                producto_id: 'prod-001',
                descripcion: 'Almendra Natural 1kg',
                cantidad: 20,
                precio_unitario: 380.00,
                descuento_pct: 5,
                impuesto_pct: 15,
            },
            {
                id: 'ovl-002',
                producto_id: 'prod-006',
                descripcion: 'Café Molido Especial 500g',
                cantidad: 50,
                precio_unitario: 120.00,
                descuento_pct: 0,
                impuesto_pct: 0,
            },
        ],
    },
    {
        id: 'ov-002',
        numero_documento: 'OV-000002',
        fecha: '2026-02-18',
        cliente_id: 'bp-004',
        vendedor: 'María López',
        almacen_id: 'wh-001',
        estado: 'Enviada',
        observaciones: '',
        lineas: [
            {
                id: 'ovl-003',
                producto_id: 'prod-004',
                descripcion: 'Escáner Código de Barras USB',
                cantidad: 3,
                precio_unitario: 2200.00,
                descuento_pct: 10,
                impuesto_pct: 15,
            },
        ],
    },
    {
        id: 'ov-003',
        numero_documento: 'OV-000003',
        fecha: '2026-02-20',
        cliente_id: 'bp-006',
        vendedor: 'Carlos Ramos',
        almacen_id: 'wh-002',
        estado: 'Borrador',
        observaciones: 'Pendiente confirmación de precios',
        lineas: [
            {
                id: 'ovl-004',
                producto_id: 'prod-003',
                descripcion: 'Aceite Hidráulico ISO 46 – 20L',
                cantidad: 5,
                precio_unitario: 1450.00,
                descuento_pct: 0,
                impuesto_pct: 15,
            },
        ],
    },
    {
        id: 'ov-004',
        numero_documento: 'OV-000004',
        fecha: '2026-02-22',
        cliente_id: 'bp-001',
        vendedor: 'Juan Pérez',
        almacen_id: 'wh-001',
        estado: 'Cancelada',
        observaciones: 'Cliente canceló el pedido',
        lineas: [
            {
                id: 'ovl-005',
                producto_id: 'prod-008',
                descripcion: 'Etiquetadora Térmica 4" USB',
                cantidad: 2,
                precio_unitario: 4800.00,
                descuento_pct: 5,
                impuesto_pct: 15,
            },
        ],
    },
];
