export const salesOrders = [
    {
        id: 'so-001',
        numero_documento: 'OC-000001',
        oferta_ref: 'OV-000001',
        fecha: '2026-02-16',
        fecha_entrega: '2026-02-28',
        cliente_id: 'bp-001',
        vendedor: 'Juan Pérez',
        almacen_id: 'wh-001',
        condicion_pago: '30 días',
        estado: 'Entregada',
        observaciones: 'Entregado completo',
        lineas: [
            { id: 'sol-001', producto_id: 'prod-001', descripcion: 'Almendra Natural 1kg', cantidad: 20, precio_unitario: 380.00, descuento_pct: 5, impuesto_pct: 15 },
            { id: 'sol-002', producto_id: 'prod-006', descripcion: 'Café Molido Especial 500g', cantidad: 50, precio_unitario: 120.00, descuento_pct: 0, impuesto_pct: 0 },
        ],
    },
    {
        id: 'so-002',
        numero_documento: 'OC-000002',
        oferta_ref: 'OV-000002',
        fecha: '2026-02-19',
        fecha_entrega: '2026-03-05',
        cliente_id: 'bp-004',
        vendedor: 'María López',
        almacen_id: 'wh-001',
        condicion_pago: '30 días',
        estado: 'En Proceso',
        observaciones: '',
        lineas: [
            { id: 'sol-003', producto_id: 'prod-004', descripcion: 'Escáner Código de Barras USB', cantidad: 3, precio_unitario: 2200.00, descuento_pct: 10, impuesto_pct: 15 },
        ],
    },
    {
        id: 'so-003',
        numero_documento: 'OC-000003',
        oferta_ref: '',
        fecha: '2026-03-01',
        fecha_entrega: '2026-03-15',
        cliente_id: 'bp-006',
        vendedor: 'Carlos Ramos',
        almacen_id: 'wh-002',
        condicion_pago: '15 días',
        estado: 'Confirmada',
        observaciones: 'Cliente solicitó entrega parcial',
        lineas: [
            { id: 'sol-004', producto_id: 'prod-002', descripcion: 'Caja Cartón Triple Canal 60x40', cantidad: 100, precio_unitario: 45.00, descuento_pct: 0, impuesto_pct: 15 },
        ],
    },
];
